### ISSUE TITLE
undefined method 'nav_link_to' when setting action_controller.include_all_helpers = false

### ISSUE THREAD

**Issue by kikocastro** [vigetlabs/nav_lynx#14]
Hi,

When I set the config

#config/application.rb
`action_controller.include_all_helpers = false`

I get

`undefined method 'nav_link_to'`

Then I put 

#application_helper.rb
  `include ActionView::Helpers::NavLinkHelper`

And it worked locally, but when I pushed to heroku I got
`ERROR -- : uninitialized constant ActionView::Helpers::NavLinkHelper (NameError)`

**Comment by kikocastro** [comment]
Solved with:

#config/initializers/init.rb
```
ActionView::Base.send :include, NavLinkHelper
```

**Comment by brianjlandau** [comment]
Probably because you were using the wrong constant name on your first try. You used `ActionView::Helpers::NavLinkHelper`. Instead in your controller you should have done: `helper NavLinkHelper` Hope that helps.

**Comment by kikocastro** [comment]
Oh, right! Thanks :)
